export const services = [
  { id: 1, name: 'ServerStatus', desc: '服务器监控与状态聚合', category: '监控', status: 'running', local: 'v1.2.0', remote: 'v1.3.0', github: 'github.com/cppla/ServerStatus', lan: '192.168.1.10:8080', wan: 'status.example.com', docker: 'serverstatus', updated: '2分钟前', icon: 'pulse', favorite: true },
  { id: 2, name: '财务系统', desc: '家庭账本与收支分析', category: '业务', status: 'running', local: 'v2.0.1', remote: 'v2.0.1', github: 'github.com/homelab/finance', lan: '192.168.1.12:3000', wan: 'money.example.com', docker: 'finance-web', updated: '18分钟前', icon: 'chart', favorite: true },
  { id: 3, name: 'NAS', desc: '文件存储与媒体中心', category: '存储', status: 'maintenance', local: 'DSM 7.2', remote: '-', github: '', lan: '192.168.1.20:5000', wan: 'nas.example.com', docker: '6 个容器', updated: '1小时前', icon: 'storage', favorite: false },
  { id: 4, name: 'Uptime Kuma', desc: '站点可用性监控', category: '监控', status: 'running', local: '1.23.15', remote: '1.23.15', github: 'github.com/louislam/uptime-kuma', lan: '192.168.1.10:3001', wan: 'uptime.example.com', docker: 'uptime-kuma', updated: '3小时前', icon: 'uptime', favorite: false },
  { id: 5, name: 'Immich', desc: '自托管照片管理', category: '媒体', status: 'warning', local: 'v1.118.2', remote: 'v1.119.0', github: 'github.com/immich-app/immich', lan: '192.168.1.20:2283', wan: 'photos.example.com', docker: 'immich-server', updated: '昨天', icon: 'photo', favorite: false },
  { id: 6, name: 'Vaultwarden', desc: '密码保险箱服务', category: '安全', status: 'running', local: '1.32.5', remote: '1.32.5', github: 'github.com/dani-garcia/vaultwarden', lan: '192.168.1.10:8082', wan: 'vault.example.com', docker: 'vaultwarden', updated: '昨天', icon: 'vault', favorite: false }
]
export const stats = [{ label: '服务总数', value: '12', change: '+2 本月', icon: 'service', tone: 'cyan' }, { label: '运行中', value: '10', change: '83.3% 正常', icon: 'running', tone: 'green' }, { label: '版本更新', value: '2', change: '需要关注', icon: 'update', tone: 'orange' }, { label: '异常服务', value: '1', change: '较昨日 -1', icon: 'alert', tone: 'red' }]
