<script setup>
import { ref, computed } from 'vue'
import { ArrowUpRight, Box, Connection, Search, Refresh, MoreFilled } from '@element-plus/icons-vue'
import { services } from '../data'
const query = ref(''); const status = ref('全部')
const filtered = computed(() => services.filter(s => (!query.value || s.name.toLowerCase().includes(query.value.toLowerCase()) || s.desc.includes(query.value)) && (status.value === '全部' || s.status === 'running')))
function open(url) { window.open(url, '_blank') }
</script>
<template><div class="page-head"><div><div class="eyebrow">SERVICE REGISTRY</div><h1>我的服务</h1><p>集中管理所有项目、入口和当前运行状态。</p></div><el-button type="primary"><el-icon><Refresh /></el-icon>检测全部</el-button></div><section class="table-panel"><div class="table-toolbar"><div class="table-search"><el-icon><Search /></el-icon><input v-model="query" placeholder="搜索项目名称或描述" /></div><el-select v-model="status" size="default" style="width:130px"><el-option label="全部状态" value="全部"/><el-option label="运行中" value="运行中"/></el-select><span class="table-count">共 {{ filtered.length }} 个项目</span></div><el-table :data="filtered" class="service-table"><el-table-column label="项目名称" min-width="220"><template #default="{ row }"><div class="project-cell"><div class="mini-logo">{{ row.name.slice(0,1) }}</div><div><strong>{{ row.name }}</strong><span>{{ row.desc }}</span></div></div></template></el-table-column><el-table-column label="状态" width="120"><template #default="{ row }"><el-tag :type="row.status === 'running' ? 'success' : row.status === 'maintenance' ? 'info' : 'warning'" effect="dark" size="small">{{ row.status === 'running' ? '运行中' : row.status === 'maintenance' ? '维护中' : '有更新' }}</el-tag></template></el-table-column><el-table-column label="版本" width="160"><template #default="{ row }"><span class="version-cell">{{ row.local }} <b v-if="row.local !== row.remote && row.remote !== '-'">→ {{ row.remote }}</b></span></template></el-table-column><el-table-column label="访问入口" min-width="230"><template #default="{ row }"><div class="entry-links"><button @click="open('http://' + row.lan)"><Connection /> LAN</button><button @click="open('https://' + row.wan)"><ArrowUpRight /> WAN</button></div></template></el-table-column><el-table-column label="Docker" width="150"><template #default="{ row }"><span class="docker-cell"><Box />{{ row.docker }}</span></template></el-table-column><el-table-column label="操作" width="90"><template #default><el-button link><MoreFilled /></el-button></template></el-table-column></el-table></section></template>
