<script setup>
import { computed, ref } from 'vue'
import { ArrowUpRight, Box, Check, CircleCheckFilled, Clock, Connection, DataAnalysis, MoreFilled, Refresh, TrendCharts, WarningFilled } from '@element-plus/icons-vue'
import { services, stats } from '../data'
const filter = ref('全部'); const filters = ['全部', '运行中', '有更新', '维护中']
const visible = computed(() => services.filter(s => filter.value === '全部' || (filter.value === '运行中' && s.status === 'running') || (filter.value === '有更新' && s.local !== s.remote && s.remote !== '-') || (filter.value === '维护中' && s.status === 'maintenance')).slice(0, 6))
const statusMeta = { running: ['运行中', 'success'], warning: ['有更新', 'warning'], maintenance: ['维护中', 'info'], error: ['异常', 'danger'], offline: ['离线', 'info'] }
function open(url) { if (url) window.open(url.startsWith('http') ? url : `https://${url}`, '_blank') }
</script>
<template>
  <div class="page-head"><div><div class="eyebrow">WED · 12 AUG 2026 <span class="live-dot"></span> LIVE</div><h1>系统概览</h1><p>欢迎回来，admin。这里是你的 HomeLab 控制中心。</p></div><el-button class="refresh-btn" plain><el-icon><Refresh /></el-icon>刷新状态</el-button></div>
  <section class="stats-grid"><div v-for="stat in stats" :key="stat.label" class="stat-card"><div class="stat-top"><span>{{ stat.label }}</span><div class="stat-icon" :class="stat.tone"><TrendCharts v-if="stat.icon === 'service'" /><CircleCheckFilled v-else-if="stat.icon === 'running'" /><Clock v-else-if="stat.icon === 'update'" /><WarningFilled v-else /></div></div><div class="stat-value">{{ stat.value }}</div><div class="stat-change" :class="stat.tone">{{ stat.change }}</div></div></section>
  <section class="section"><div class="section-heading"><div><h2>我的服务</h2><span class="section-sub">6 个常用服务 · 最近同步于 2 分钟前</span></div><div class="heading-actions"><div class="filter-tabs"><button v-for="item in filters" :key="item" :class="{ selected: filter === item }" @click="filter = item">{{ item }}</button></div><el-button link>查看全部 <el-icon><ArrowUpRight /></el-icon></el-button></div></div>
    <div class="services-grid"><article v-for="service in visible" :key="service.id" class="service-card"><div class="service-card-head"><div class="service-logo" :class="service.icon"><TrendCharts v-if="service.icon === 'pulse'" /><el-icon v-else><DataAnalysis /></el-icon></div><div class="service-title"><h3>{{ service.name }}</h3><span>{{ service.desc }}</span></div><el-icon class="more"><MoreFilled /></el-icon></div><div class="service-meta"><el-tag :type="statusMeta[service.status][1]" effect="dark" size="small"><i class="status-dot"></i>{{ statusMeta[service.status][0] }}</el-tag><span class="category">{{ service.category }}</span><span class="updated"><Clock /> {{ service.updated }}</span></div><div class="version-row"><div><span>当前版本</span><strong>{{ service.local }}</strong></div><div v-if="service.remote !== '-'" class="version-latest"><span>GitHub 最新</span><strong>{{ service.remote }}</strong></div><div v-if="service.local !== service.remote && service.remote !== '-'" class="update-pill">有新版本</div></div><div class="service-links"><button @click="open(`http://${service.lan}`)"><el-icon><Connection /></el-icon>内网访问</button><button @click="open(`https://${service.wan}`)"><el-icon><ArrowUpRight /></el-icon>公网访问</button><button v-if="service.github" @click="open(`https://${service.github}`)"><el-icon><Box /></el-icon>GitHub</button></div></article></div>
  </section>
  <div class="lower-grid"><section class="panel"><div class="panel-heading"><div><h2>最近更新</h2><span class="section-sub">系统活动与版本提醒</span></div><el-button link>全部记录</el-button></div><div class="activity-list"><div class="activity"><div class="activity-icon orange"><Clock /></div><div><strong>ServerStatus 发现新版本</strong><p>v1.2.0 → v1.3.0</p></div><time>2分钟前</time></div><div class="activity"><div class="activity-icon green"><Check /></div><div><strong>财务系统检测完成</strong><p>当前版本已是最新</p></div><time>18分钟前</time></div><div class="activity"><div class="activity-icon blue"><Refresh /></div><div><strong>NAS 进入维护状态</strong><p>计划维护 · 预计 30 分钟</p></div><time>1小时前</time></div></div></section><section class="panel"><div class="panel-heading"><div><h2>基础设施</h2><span class="section-sub">主节点 · 192.168.1.10</span></div><el-tag type="success" effect="plain">在线</el-tag></div><div class="resource"><div class="resource-label"><span>CPU 使用率</span><strong>32%</strong></div><div class="progress"><i style="width:32%"></i></div></div><div class="resource"><div class="resource-label"><span>内存</span><strong>61%</strong></div><div class="progress"><i class="yellow" style="width:61%"></i></div></div><div class="resource"><div class="resource-label"><span>存储空间</span><strong>74%</strong></div><div class="progress"><i class="orange" style="width:74%"></i></div></div><div class="infra-foot"><span><b>18</b> / 20 容器运行</span><span class="healthy"><CircleCheckFilled /> 所有节点健康</span></div></section></div>
</template>
